CREATE TABLE `pacientes` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `idTipoDoc_id` bigint(20) NOT NULL,
  `numDoc` varchar(50) NOT NULL,
  `nombre` varchar(50) NOT NULL,
  `apellido` varchar(50) NOT NULL,
  `fechaNac` date NOT NULL,
  `sexo` varchar(1) NOT NULL,
  `mail` varchar(50) DEFAULT NULL,
  `direccion` varchar(100) DEFAULT NULL,
  `localidad` varchar(60) DEFAULT NULL,
  `obraSocial` varchar(50) NOT NULL,
  `plan` varchar(50) DEFAULT NULL,
  `afiliado` varchar(50) NOT NULL,
  `telefono` varchar(50) NOT NULL,
  `celular` varchar(50) NOT NULL,
  `profesion` varchar(50) NOT NULL,
  `referente` varchar(50) DEFAULT NULL,
  `fechaAlta` date NOT NULL,
  `deBaja` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pacientes_idTipoDoc_numDoc_c2558d0d_uniq` (`idTipoDoc_id`,`numDoc`),
  KEY `nombre_idx` (`nombre`),
  KEY `apellido_idx` (`apellido`),
  KEY `paciente_fechaAlta_idx` (`fechaAlta`),
  KEY `pacientes_idTipoDoc_id_6d4a5435` (`idTipoDoc_id`),
  FULLTEXT KEY `nombre_apellido_idx` (`nombre`,`apellido`),
  CONSTRAINT `pacientes_idTipoDoc_id_6d4a5435_fk_main_tipodocumento_id` FOREIGN KEY (`idTipoDoc_id`) REFERENCES `main_tipodocumento` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
