"""
Django settings for hhcc project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s6t!(@**v#55u-0bxn52i4c83q*ydsu82#_&q#0d0i&g1%=^!*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


SHELL_PLUS = "ipython"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'main',
    'ecocardiograma',
    'carotidas',
    'ecostress',
    'mmii',
    'Qbi2.apps.Qbi2Config',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hhcc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            #    'main.context_processors.menu_context'
            ],
        },
    },
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


CORS_ALLOWED_ORIGINS = [
        "http://localhost:8080",
        "http://localhost:9999",
]

CORS_ALLOW_ALL_ORIGINS = True # Sacar en produccion

WSGI_APPLICATION = 'hhcc.wsgi.application'

X_FRAME_OPTIONS = 'ALLOWALL'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.mysql")
DB_NAME = os.getenv("DB_NAME", "cardioprieto")
DB_USER = os.getenv("DB_USER", "root")
DB_PASSWORD = os.getenv("DB_PASSWORD", "Corbis5")
DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
DB_PORT = os.getenv("DB_PORT", "3307")

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    },
    "sandbox": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# En local, permitimos contraseñas simples para evitar bloqueos en UI.
# Ajustar/endurcer antes de producción.
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE =  'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('es', 'Español'),
    ('es-ar', 'Español (Argentina)'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'

DATE_INPUT_FORMATS = [
    '%d/%m/%Y',    # 25/12/2023
    '%d-%m-%Y',    # 25-12-2023
    '%Y-%m-%d',    # 2023-12-25
    '%d/%m/%y',    # 25/12/23
    '%d-%m-%y',    # 25-12-23
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M:%S',
    '%d/%m/%Y %H:%M',
    '%d-%m-%Y %H:%M:%S',
    '%d-%m-%Y %H:%M',
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d %H:%M',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static'),
    os.path.join(BASE_DIR, 'ecocardiograma/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def load_local_env_file(path):
    """Carga pares KEY=VALUE simples sin pisar variables ya exportadas."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


# Qbi2 / RCTA Recipe
# Las credenciales deben venir del entorno. El modo "auto" envia Bearer solo si
# hay token configurado, porque algunos endpoints de catalogo podrian ser publicos.
load_local_env_file(Path(os.getenv("QBI2_ENV_FILE", BASE_DIR.parent / ".env.qbi2")))
QBI2_BASE_URL = os.getenv("QBI2_BASE_URL", "https://apirecipe.hml.qbitos.com/")
QBI2_BEARER_TOKEN = os.getenv("QBI2_BEARER_TOKEN", "")
QBI2_CLIENT_APP_ID = os.getenv("QBI2_CLIENT_APP_ID", "563")
QBI2_TIMEOUT_SECONDS = float(os.getenv("QBI2_TIMEOUT_SECONDS", "15"))
QBI2_AUTH_MODE = os.getenv("QBI2_AUTH_MODE", "auto")  # auto|required|none
QBI2_VADEMECUM_PATH = os.getenv("QBI2_VADEMECUM_PATH", "/apirecipe/GetMedicamento/{search}")
QBI2_VADEMECUM_PAGE_PARAM = os.getenv("QBI2_VADEMECUM_PAGE_PARAM", "numeroPagina")
QBI2_CLIENT_APP_ID_PARAM = os.getenv("QBI2_CLIENT_APP_ID_PARAM", "clienteAppId")
QBI2_INCLUDE_CLIENT_APP_ID_IN_VADEMECUM = os.getenv(
    "QBI2_INCLUDE_CLIENT_APP_ID_IN_VADEMECUM",
    "1",
) == "1"
QBI2_VADEMECUM_MIN_QUERY_LENGTH = int(os.getenv("QBI2_VADEMECUM_MIN_QUERY_LENGTH", "2"))
