# Generated by Django 5.0.7 on 2024-08-10 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer'), ('f', 'Femenino')], max_length=1)),
                ('debaja', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numdoc', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('afiliado', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(max_length=100)),
                ('fechanac', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaalta', models.DateField()),
                ('localidad', models.CharField(max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('referente', models.CharField(blank=True, max_length=100, null=True)),
                ('obrasocial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaalta', models.DateField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='idtipodoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento')),
            ],
        ),
    ]
