# Generated by Django 5.0.7 on 2024-08-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedente',
            old_name='condicion',
            new_name='condicion_medica',
        ),
    ]
