# Generated by Django 5.1.1 on 2024-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'enfermedades',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
