# Generated by Django 5.1.1 on 2024-12-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField()),
                ('historia_clinica', models.ForeignKey(db_column='idHistoriaClinica', on_delete=django.db.models.deletion.CASCADE, to='main.historiaclinica')),
            ],
            options={
                'db_table': 'comentarios_visitas',
                'indexes': [models.Index(fields=['fecha'], name='comentarios_fecha_f1595a_idx'), models.Index(fields=['historia_clinica'], name='comentarios_idHisto_e55c6a_idx'), models.Index(fields=['fecha', 'historia_clinica'], name='comentarios_fecha_f65e9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicacionesVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('indicaciones', models.TextField()),
                ('historia_clinica', models.ForeignKey(db_column='idHistoriaClinica', on_delete=django.db.models.deletion.CASCADE, to='main.historiaclinica')),
            ],
            options={
                'db_table': 'indicaciones_visitas',
                'indexes': [models.Index(fields=['fecha'], name='indicacione_fecha_b762b7_idx'), models.Index(fields=['historia_clinica'], name='indicacione_idHisto_248eeb_idx'), models.Index(fields=['fecha', 'historia_clinica'], name='indicacione_fecha_db5560_idx')],
            },
        ),
    ]
