# Generated by Django 5.0.7 on 2024-08-11 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='fechaalta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
