# Generated by Django 5.1.1 on 2024-12-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comentariosvisitas_indicacionesvisitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosvisitas',
            name='tipo',
            field=models.CharField(choices=[('EVOL', 'Evolución'), ('INDIC', 'Indicaciones')], default='EVOL', max_length=5),
        ),
    ]
