# Generated by Django 5.0.7 on 2024-08-26 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_condicion_antecedente_condicion_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
