# Generated by Django 5.1.1 on 2026-02-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_inx_fix_sexo'),
    ]

    def _safe_rename_indexes(apps, schema_editor):
        def index_exists(cursor, table, index):
            cursor.execute(
                """
                SELECT COUNT(1)
                FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND INDEX_NAME = %s
                """,
                [table, index],
            )
            return cursor.fetchone()[0] > 0

        def drop_index(cursor, table, index):
            cursor.execute(f"DROP INDEX `{index}` ON `{table}`")

        def rename_index(cursor, table, old, new):
            cursor.execute(f"ALTER TABLE `{table}` RENAME INDEX `{old}` TO `{new}`")

        with schema_editor.connection.cursor() as cursor:
            # historias_clinicas: idPaciente_idx -> historia_paciente_idx
            if index_exists(cursor, "historias_clinicas", "idPaciente_idx"):
                if index_exists(cursor, "historias_clinicas", "historia_paciente_idx"):
                    drop_index(cursor, "historias_clinicas", "idPaciente_idx")
                else:
                    rename_index(cursor, "historias_clinicas", "idPaciente_idx", "historia_paciente_idx")

            # indicaciones_visitas: ind_fecha_idx -> indicaciones_fecha_idx
            if index_exists(cursor, "indicaciones_visitas", "ind_fecha_idx"):
                if index_exists(cursor, "indicaciones_visitas", "indicaciones_fecha_idx"):
                    drop_index(cursor, "indicaciones_visitas", "ind_fecha_idx")
                else:
                    rename_index(cursor, "indicaciones_visitas", "ind_fecha_idx", "indicaciones_fecha_idx")

            # indicaciones_visitas: ind_his_fecha_idx -> ind_hist_fecha_idx
            if index_exists(cursor, "indicaciones_visitas", "ind_his_fecha_idx"):
                if index_exists(cursor, "indicaciones_visitas", "ind_hist_fecha_idx"):
                    drop_index(cursor, "indicaciones_visitas", "ind_his_fecha_idx")
                else:
                    rename_index(cursor, "indicaciones_visitas", "ind_his_fecha_idx", "ind_hist_fecha_idx")

    operations = [
        migrations.RunPython(_safe_rename_indexes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDoc',
            field=models.ForeignKey(db_column='idTipoDoc_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
        migrations.AddIndex(
            model_name='indicacionesvisitas',
            index=models.Index(fields=['historia_clinica'], name='indicaciones_historia_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['idTipoDoc'], name='pacientes_tipo_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['historia'], name='signos_vitales_historia_idx'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['fecha'], name='signos_vitales_fecha_idx'),
        ),
    ]
