# Generated by Django 5.1.1 on 2024-10-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('idTipoDoc', 'numDoc')},
        ),
        migrations.DeleteModel(
            name='Identificacion',
        ),
    ]
