# Generated by Django 5.1.1 on 2026-04-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_idpaciente_idx_historia_paciente_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="historiaclinica",
                    old_name="idPaciente_idx",
                    new_name="historia_paciente_idx",
                ),
                migrations.RenameIndex(
                    model_name="indicacionesvisitas",
                    old_name="ind_fecha_idx",
                    new_name="indicaciones_fecha_idx",
                ),
                migrations.RenameIndex(
                    model_name="indicacionesvisitas",
                    old_name="ind_his_fecha_idx",
                    new_name="ind_hist_fecha_idx",
                ),
            ],
        ),
    ]
