# Generated by Django 5.1.1 on 2024-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_paciente_unique_together_delete_identificacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paciente',
            new_name='nombre_paciente_idx',
            old_name='nombre_idx',
        ),
        migrations.RenameIndex(
            model_name='paciente',
            new_name='apellido_paciente_idx',
            old_name='apellido_idx',
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['nombre'], name='nombre_tipodocumento_idx'),
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='tipos_documentos',
        ),
    ]
