# Generated by Django 5.1.1 on 2025-01-16 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comentariosvisitas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='condiciones',
            field=models.ManyToManyField(through='main.CondicionMedicaHistoria', to='main.condicionmedica'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
