# Generated by Django 5.1.1 on 2025-05-22 20:40

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_conclusiónecocardiograma_estudioecocardiograma_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idHC ON indicaciones_visitas;",
            reverse_sql="CREATE INDEX idHC ON indicaciones_visitas (historia_clinica_id);"
        ),
        migrations.AddIndex(
            model_name="indicacionesvisitas",
            index=models.Index(fields=["fecha"], name="indicacione_fecha_b762b7_idx"),
        ),
        migrations.AddIndex(
            model_name="indicacionesvisitas", 
            index=models.Index(fields=["historia_clinica"], name="indicacione_histori_e75187_idx"),
        ),
        migrations.AddIndex(
            model_name="indicacionesvisitas",
            index=models.Index(fields=["historia_clinica", "fecha"], name="indicacione_histori_4b9d3d_idx"),
        ),
    ]
