# Generated by Django 5.1.1 on 2024-10-10 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_nombre_idx_nombre_paciente_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idTipoDoc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDoc',
            field=models.IntegerField(),
        ),
    ]
