# Generated by Django 5.1.1 on 2024-10-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paciente_idtipodoc_id_alter_paciente_idtipodoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idTipoDoc_id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
    ]
