# Generated by Django 5.1.1 on 2024-10-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_paciente_idtipodoc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
    ]
