# Generated by Django 5.1.1 on 2024-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_paciente_idtipodoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idTipoDoc_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
