# Generated by Django 5.1.1 on 2026-05-22 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_global_search_trigrams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_reg_no', models.CharField(max_length=50)),
                ('medicamento_nombre_producto', models.CharField(blank=True, max_length=255)),
                ('medicamento_nombre_droga', models.CharField(blank=True, max_length=255)),
                ('medicamento_presentacion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('emitida', 'Emitida'), ('error_emision', 'Error de emision'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('observacion_paciente', models.TextField(blank=True)),
                ('observacion_medico', models.TextField(blank=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('payload_qbi2', models.JSONField(blank=True, default=dict)),
                ('respuesta_qbi2', models.JSONField(blank=True, default=dict)),
                ('error_qbi2', models.TextField(blank=True)),
                ('qbi2_id_receta', models.CharField(blank=True, max_length=100)),
                ('qbi2_pdf_url', models.URLField(blank=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_user_agent', models.TextField(blank=True)),
                ('auditoria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qbi2_solicitudes_receta_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qbi2_solicitudes_receta', to='main.historiaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qbi2_solicitudes_receta', to='main.paciente')),
            ],
            options={
                'db_table': 'qbi2_solicitudes_receta',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='qbi2_sol_estado_fecha_idx'), models.Index(fields=['paciente', '-created_at'], name='qbi2_sol_paciente_fecha_idx'), models.Index(fields=['medicamento_reg_no'], name='qbi2_sol_regno_idx')],
            },
        ),
    ]
