# Generated by Django 5.1.1 on 2026-05-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbi2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreceta',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitudreceta',
            name='posologia',
            field=models.TextField(blank=True),
        ),
    ]
